### ISSUE TITLE
preprocessing error

### ISSUE THREAD

**Issue by dohyun-as** [mui-neuro/swi-cnn#4]
when I run `swi-cnn.py -s example_subject --preproc` I encounter an error:

Using TensorFlow backend.
Preprocessing data...
Conforming data to isotropic resolution 0.687500
All data conformed to isotropic resolution!

Creating brainmasks...

bet /home/kdh/preproc/example_subject.nii.gz /home/kdh/preproc/example_subject_brain.nii.gz -m -R -f 0.500000
Traceback (most recent call last):
  File "/home/kdh/KDH/SN_segmentation/swi-cnn/swi-cnn.py", line 137, in <module>
    ut.create_swi_brainmask(config, config['preproc_dir'])
  File "/home/kdh/KDH/SN_segmentation/swi-cnn/utils.py", line 1656, in create_swi_brainmask
    run(cmd)
  File "/home/kdh/KDH/SN_segmentation/swi-cnn/utils.py", line 89, in run
    p = Popen(shlex.split(cmd), stdout=PIPE, stderr=PIPE)
  File "/home/kdh/anaconda3/envs/swi-cnn/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/kdh/anaconda3/envs/swi-cnn/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bet': 'bet'

How can I solve this?

**Comment by dohyun-as** [comment]
I can solve this problem by installing FSL.
